name: Test

on:
  pull_request:
    branches:
      - master
      - develop
  push:
    branches:
      - master
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/hydrogen"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install pre-commit
          cd nextjs && npm ci

      - name: Run pre-commit
        run: pre-commit run --all-files

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up workflow with Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/hydrogen"

      - name: Remove .env file
        run: |
          rm -f .env

      - name: Create .env file
        run: |
          echo "ENVIRONMENT=prod" >> .env
          echo "NEXT_PUBLIC_SITE_NAME={{PROJECT_NAME}}" >> .env
          echo "NEXT_PUBLIC_SITE_BASE_DOMAIN=https://{{DOMAIN_PRODUCTION}}" >> .env
          echo "SITE_DOMAIN={{DOMAIN_PRODUCTION}}" >> .env
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
          echo "DJANGO_SETTINGS_MODULE=settings" >> .env
          echo "POSTGRES_DB={{DB_NAME}}" >> .env
          echo "POSTGRES_USER={{DB_USER}}" >> .env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
          echo "REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}" >> .env
          echo "REDIS_HOST=redis" >> .env
          echo "EMAIL_HOST=smtp.sendgrid.net" >> .env
          echo "EMAIL_HOST_USER=apikey" >> .env
          echo "EMAIL_HOST_PASSWORD=${{ secrets.EMAIL_HOST_PASSWORD }}" >> .env
          echo "STRIPE_PUBLISHABLE_KEY=${{ secrets.STRIPE_PUBLISHABLE_KEY }}" >> .env
          echo "STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }}" >> .env
          echo "STRIPE_WEBHOOK_SECRET=${{ secrets.STRIPE_WEBHOOK_SECRET }}" >> .env
          echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> .env
          echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> .env
          echo "SENTRY_DSN=${{ secrets.SENTRY_DSN }}" >> .env

      - name: Install Python dependencies; create Django static directory
        run: |
          cd ./web
          pip install -r requirements.txt
          python manage.py collectstatic --noinput

      - name: Build Docker containers
        run: |
          docker compose -f docker-compose.yaml -f docker-compose.prod.yaml up --build -d || {
            echo "=== Docker compose failed, capturing logs ==="
            docker ps -a
            echo "=== Django container logs ==="
            docker logs {{PROJECT_SLUG}}-django 2>&1 || true
            echo "=== Postgres container logs ==="
            docker logs {{PROJECT_SLUG}}-postgres 2>&1 || true
            exit 1
          }

      - name: Wait for Django container to be healthy
        timeout-minutes: 4
        run: |
          set -e

          docker logs -f {{PROJECT_SLUG}}-django &
          LOG_PID=$!

          trap "echo 'Stop'; kill $LOG_PID" EXIT

          end=$((SECONDS+300))
          while [ $SECONDS -lt $end ]; do
            STATUS="$(docker inspect --format='{{.State.Health.Status}}' {{PROJECT_SLUG}}-django || echo 'none')"
            if [ "$STATUS" = "healthy" ]; then
              echo "Django container is healthy!"
              echo "-------------------------------------------------"
              docker ps -a
              echo "-------------------------------------------------"
              kill $LOG_PID
              exit 0
            fi

            echo "-------------------------------------------------"
            echo "Waiting for Django container to be healthy..."
            echo "Status: $STATUS"
            echo "-------------------------------------------------"
            sleep 5
          done
          echo "Timed out waiting for Django container to be healthy."
          echo "-------------------------------------------------"
          docker ps -a
          echo "-------------------------------------------------"
          kill $LOG_PID
          exit 1

      - name: Run Django tests
        run: |
          docker exec {{PROJECT_SLUG}}-django python manage.py test

      - name: Wait for Next.js container to be healthy
        timeout-minutes: 2
        run: |
          set -e

          docker logs -f {{PROJECT_SLUG}}-nextjs &
          LOG_PID=$!

          trap "echo 'Stop'; kill $LOG_PID" EXIT

          end=$((SECONDS+300))
          while [ $SECONDS -lt $end ]; do
            STATUS="$(docker inspect --format='{{.State.Health.Status}}' {{PROJECT_SLUG}}-nextjs || echo 'none')"
            if [ "$STATUS" = "healthy" ]; then
              echo "Next.js container is healthy!"
              echo "-------------------------------------------------"
              docker ps -a
              echo "-------------------------------------------------"
              kill $LOG_PID
              exit 0
            fi

            echo "-------------------------------------------------"
            echo "Waiting for Next.js container to be healthy..."
            echo "Status: $STATUS"
            echo "-------------------------------------------------"
            sleep 5
          done
          echo "Timed out waiting for Next.js container to be healthy."
          echo "-------------------------------------------------"
          docker ps -a
          echo "-------------------------------------------------"
          kill $LOG_PID
          exit 1

      - name: Bring down Docker containers
        run: docker compose down
